"""Dump the OpenAPI schema to a JSON file."""

import json

from django.core.management.base import BaseCommand
from drf_spectacular.generators import SchemaGenerator


class Command(BaseCommand):
    help = "Export the OpenAPI schema generated by drf-spectacular to a JSON file."

    def add_arguments(self, parser):
        parser.add_argument("output", type=str, help="Output file path for the JSON schema.")

    def handle(self, *args, **options):
        generator = SchemaGenerator()
        schema = generator.get_schema(request=None, public=True)
        output_path = options["output"]
        with open(output_path, "w") as f:
            json.dump(schema, f, indent=2, default=str)
        self.stdout.write(self.style.SUCCESS(f"Schema written to {output_path}"))
