# Generated by Django 4.0.3 on 2022-03-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usersec", "0005_hpcgroupchangerequest_editor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hpcuser",
            name="email",
        ),
        migrations.RemoveField(
            model_name="hpcuser",
            name="first_names",
        ),
        migrations.RemoveField(
            model_name="hpcuser",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="hpcuser",
            name="surname",
        ),
        migrations.RemoveField(
            model_name="hpcuserversion",
            name="email",
        ),
        migrations.RemoveField(
            model_name="hpcuserversion",
            name="first_names",
        ),
        migrations.RemoveField(
            model_name="hpcuserversion",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="hpcuserversion",
            name="surname",
        ),
        migrations.AlterField(
            model_name="hpcgroup",
            name="resources_used",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hpcgroupchangerequest",
            name="comment",
            field=models.TextField(
                default="nothing to say",
                help_text="Comment request or summarize revision",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hpcgroupchangerequestversion",
            name="comment",
            field=models.TextField(
                default="nothing to say",
                help_text="Comment request or summarize revision",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hpcgroupcreaterequest",
            name="comment",
            field=models.TextField(
                default="nothing to say",
                help_text="Comment request or summarize revision",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hpcgroupcreaterequestversion",
            name="comment",
            field=models.TextField(
                default="nothing to say",
                help_text="Comment request or summarize revision",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hpcgroupdeleterequest",
            name="comment",
            field=models.TextField(
                default="nothing to say",
                help_text="Comment request or summarize revision",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hpcgroupdeleterequestversion",
            name="comment",
            field=models.TextField(
                default="nothing to say",
                help_text="Comment request or summarize revision",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hpcgroupversion",
            name="resources_used",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hpcuser",
            name="resources_used",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hpcuserchangerequest",
            name="comment",
            field=models.TextField(
                default="nothing to say",
                help_text="Comment request or summarize revision",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hpcuserchangerequestversion",
            name="comment",
            field=models.TextField(
                default="nothing to say",
                help_text="Comment request or summarize revision",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hpcusercreaterequest",
            name="comment",
            field=models.TextField(
                default="nothing to say",
                help_text="Comment request or summarize revision",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hpcusercreaterequestversion",
            name="comment",
            field=models.TextField(
                default="nothing to say",
                help_text="Comment request or summarize revision",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hpcuserdeleterequest",
            name="comment",
            field=models.TextField(
                default="nothing to say",
                help_text="Comment request or summarize revision",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hpcuserdeleterequestversion",
            name="comment",
            field=models.TextField(
                default="nothing to say",
                help_text="Comment request or summarize revision",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hpcuserversion",
            name="resources_used",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
