# Generated by Django 4.0.3 on 2022-05-06 16:56

import uuid

import django.db.models.deletion
from django.db import migrations, models

import usersec.models


class Migration(migrations.Migration):
    dependencies = [
        ("usersec", "0012_alter_hpcgroup_delegate_alter_hpcgroup_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HpcGroupInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Record UUID", unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("ACCEPTED", "ACCEPTED"),
                            ("REJECTED", "REJECTED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="PENDING",
                        help_text="Status of the project invitation",
                        max_length=16,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username the invitation is valid for", max_length=255
                    ),
                ),
                (
                    "current_version",
                    models.IntegerField(
                        help_text="Currently active version of the group invitation object"
                    ),
                ),
                (
                    "hpcusercreaterequest",
                    models.ForeignKey(
                        help_text="User create request that initiated the invitation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usersec.hpcusercreaterequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(usersec.models.VersionManagerMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HpcProjectInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Record UUID", unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("ACCEPTED", "ACCEPTED"),
                            ("REJECTED", "REJECTED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="PENDING",
                        help_text="Status of the project invitation",
                        max_length=16,
                    ),
                ),
                (
                    "current_version",
                    models.IntegerField(
                        help_text="Currently active version of the project delete request object"
                    ),
                ),
                (
                    "hpcprojectchangerequest",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project change request that initiated the invitation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usersec.hpcprojectchangerequest",
                    ),
                ),
                (
                    "hpcprojectcreaterequest",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project create request that initiated the invitation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usersec.hpcprojectcreaterequest",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project the user has been invited to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usersec.hpcproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Invited user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="usersec.hpcuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(usersec.models.VersionManagerMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HpcProjectInvitationVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Record UUID", unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("ACCEPTED", "ACCEPTED"),
                            ("REJECTED", "REJECTED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="PENDING",
                        help_text="Status of the project invitation",
                        max_length=16,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        help_text="Version number of this project invitation object"
                    ),
                ),
                (
                    "belongs_to",
                    models.ForeignKey(
                        help_text="Object this version belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_history",
                        to="usersec.hpcprojectinvitation",
                    ),
                ),
                (
                    "hpcprojectchangerequest",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project change request that initiated the invitation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usersec.hpcprojectchangerequest",
                    ),
                ),
                (
                    "hpcprojectcreaterequest",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project create request that initiated the invitation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usersec.hpcprojectcreaterequest",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project the user has been invited to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usersec.hpcproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Invited user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="usersec.hpcuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HpcGroupInvitationVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Record UUID", unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("ACCEPTED", "ACCEPTED"),
                            ("REJECTED", "REJECTED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="PENDING",
                        help_text="Status of the project invitation",
                        max_length=16,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username the invitation is valid for", max_length=255
                    ),
                ),
                (
                    "version",
                    models.IntegerField(help_text="Version number of this group invitation object"),
                ),
                (
                    "belongs_to",
                    models.ForeignKey(
                        help_text="Object this version belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_history",
                        to="usersec.hpcgroupinvitation",
                    ),
                ),
                (
                    "hpcusercreaterequest",
                    models.ForeignKey(
                        help_text="User create request that initiated the invitation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usersec.hpcusercreaterequest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
