# Generated by Django 4.0.3 on 2022-05-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usersec", "0013_hpcgroupinvitation_hpcprojectinvitation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hpcgroupchangerequest",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Concise description of what kind of computations are required for the project on the cluster",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupchangerequestversion",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Concise description of what kind of computations are required for the project on the cluster",
                max_length=512,
                null=True,
            ),
        ),
    ]
