# Generated by Django 4.0.3 on 2022-05-11 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usersec", "0014_hpcgroupchangerequest_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hpcuserchangerequest",
            name="resources_requested",
        ),
        migrations.RemoveField(
            model_name="hpcuserchangerequestversion",
            name="resources_requested",
        ),
    ]
