# Generated by Django 4.2.10 on 2024-02-16 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usersec", "0018_hpcuser_home_directory_hpcuser_login_shell_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hpcuser",
            name="primary_group",
            field=models.ForeignKey(
                help_text="Primary group the user belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcgroup",
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserversion",
            name="primary_group",
            field=models.ForeignKey(
                help_text="Primary group the user belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcgroup",
            ),
        ),
    ]
