# Generated by Django 4.2.10 on 2024-03-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usersec", "0022_hpcgroupcreaterequest_folder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hpcprojectcreaterequest",
            name="folder",
            field=models.CharField(
                blank=True,
                help_text="Path to the project folder on the cluster",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hpcprojectcreaterequest",
            name="name_requested",
            field=models.CharField(
                default="noname",
                help_text="Please use only alphanumeric characters, dashes or underscores and no spaces",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hpcprojectcreaterequestversion",
            name="folder",
            field=models.CharField(
                blank=True,
                help_text="Path to the project folder on the cluster",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hpcprojectcreaterequestversion",
            name="name_requested",
            field=models.CharField(
                default="noname",
                help_text="Please use only alphanumeric characters, dashes or underscores and no spaces",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hpcprojectcreaterequest",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="POSIX name of the project on the cluster",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectcreaterequestversion",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="POSIX name of the project on the cluster",
                max_length=64,
                null=True,
            ),
        ),
    ]
