# Generated by Django 4.2.17 on 2024-12-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersec", "0030_alter_hpcgroupchangerequest_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hpcuser",
            name="uid",
            field=models.IntegerField(
                help_text="Id of the user on the cluster", null=True
            ),
        ),
        migrations.AddField(
            model_name="hpcuserversion",
            name="uid",
            field=models.IntegerField(
                help_text="Id of the user on the cluster", null=True
            ),
        ),
    ]
