# Generated by Django 4.2.30 on 2026-10-09 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersec', '0031_hpcuser_uid_hpcuserversion_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HpcGroupChangeRequestEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Record UUID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='DateTime of last modification')),
                ('status', models.CharField(choices=[('INITIAL', 'INITIAL'), ('ACTIVE', 'ACTIVE'), ('REVISION', 'REVISION'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('RETRACTED', 'RETRACTED'), ('ARCHIVED', 'ARCHIVED')], default='INITIAL', help_text='Status of the request', max_length=16)),
                ('comment', models.TextField(blank=True, help_text='This field is for communication between you and the HPC team.', null=True)),
                ('resources_requested', models.JSONField()),
                ('description', models.CharField(blank=True, help_text='Concise description of what kind of computations are required for the project on the cluster', max_length=512, null=True)),
                ('expiration', models.DateTimeField(help_text='Expiration date of the group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcGroupCreateRequestEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Record UUID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='DateTime of last modification')),
                ('status', models.CharField(choices=[('INITIAL', 'INITIAL'), ('ACTIVE', 'ACTIVE'), ('REVISION', 'REVISION'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('RETRACTED', 'RETRACTED'), ('ARCHIVED', 'ARCHIVED')], default='INITIAL', help_text='Status of the request', max_length=16)),
                ('comment', models.TextField(blank=True, help_text='This field is for communication between you and the HPC team.', null=True)),
                ('resources_requested', models.JSONField()),
                ('name', models.CharField(blank=True, help_text='POSIX name of the group on the cluster', max_length=64, null=True)),
                ('folders', models.JSONField(blank=True, help_text='Paths to the folders of the project on the cluster', null=True)),
                ('description', models.CharField(blank=True, help_text='Concise description of what kind of computations the group performs on the cluster', max_length=512, null=True)),
                ('expiration', models.DateTimeField(help_text='Expiration date of the group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcGroupDeleteRequestEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Record UUID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='DateTime of last modification')),
                ('status', models.CharField(choices=[('INITIAL', 'INITIAL'), ('ACTIVE', 'ACTIVE'), ('REVISION', 'REVISION'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('RETRACTED', 'RETRACTED'), ('ARCHIVED', 'ARCHIVED')], default='INITIAL', help_text='Status of the request', max_length=16)),
                ('comment', models.TextField(blank=True, help_text='This field is for communication between you and the HPC team.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcGroupEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Record UUID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='DateTime of last modification')),
                ('resources_requested', models.JSONField()),
                ('resources_used', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, help_text='Concise description of what kind of computations the group performs on the cluster', max_length=512, null=True)),
                ('status', models.CharField(choices=[('INITIAL', 'INITIAL'), ('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED'), ('EXPIRED', 'EXPIRED')], default='INITIAL', help_text='Status of the group object', max_length=16)),
                ('gid', models.IntegerField(help_text='Id of the group on the cluster', null=True)),
                ('name', models.CharField(help_text='Name of the group on the cluster', max_length=64)),
                ('folders', models.JSONField(help_text='Paths to the folders of the group on the cluster')),
                ('expiration', models.DateTimeField(help_text='Expiration date of the group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcGroupInvitationEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Record UUID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='DateTime of last modification')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED')], default='PENDING', help_text='Status of the project invitation', max_length=16)),
                ('username', models.CharField(help_text='Username the invitation is valid for', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcProjectChangeRequestEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Record UUID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='DateTime of last modification')),
                ('status', models.CharField(choices=[('INITIAL', 'INITIAL'), ('ACTIVE', 'ACTIVE'), ('REVISION', 'REVISION'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('RETRACTED', 'RETRACTED'), ('ARCHIVED', 'ARCHIVED')], default='INITIAL', help_text='Status of the request', max_length=16)),
                ('comment', models.TextField(blank=True, help_text='This field is for communication between you and the HPC team.', null=True)),
                ('resources_requested', models.JSONField()),
                ('description', models.CharField(blank=True, help_text='Additional information about the user', max_length=512, null=True)),
                ('expiration', models.DateTimeField(help_text='Expiration date of the project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcProjectChangeRequestMembersEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcProjectCreateRequestEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Record UUID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='DateTime of last modification')),
                ('status', models.CharField(choices=[('INITIAL', 'INITIAL'), ('ACTIVE', 'ACTIVE'), ('REVISION', 'REVISION'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('RETRACTED', 'RETRACTED'), ('ARCHIVED', 'ARCHIVED')], default='INITIAL', help_text='Status of the request', max_length=16)),
                ('comment', models.TextField(blank=True, help_text='This field is for communication between you and the HPC team.', null=True)),
                ('resources_requested', models.JSONField()),
                ('name_requested', models.CharField(help_text='Please use only alphanumeric characters, dashes or underscores and no spaces', max_length=64)),
                ('name', models.CharField(blank=True, help_text='POSIX name of the project on the cluster', max_length=64, null=True)),
                ('folders', models.JSONField(blank=True, help_text='Paths to the folders of the project on the cluster', null=True)),
                ('description', models.CharField(blank=True, help_text='Concise description of what kind of computations are required for the project on the cluster', max_length=512, null=True)),
                ('expiration', models.DateTimeField(help_text='Expiration date of the project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcProjectCreateRequestMembersEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcProjectDeleteRequestEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Record UUID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='DateTime of last modification')),
                ('status', models.CharField(choices=[('INITIAL', 'INITIAL'), ('ACTIVE', 'ACTIVE'), ('REVISION', 'REVISION'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('RETRACTED', 'RETRACTED'), ('ARCHIVED', 'ARCHIVED')], default='INITIAL', help_text='Status of the request', max_length=16)),
                ('comment', models.TextField(blank=True, help_text='This field is for communication between you and the HPC team.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcProjectEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Record UUID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='DateTime of last modification')),
                ('resources_requested', models.JSONField()),
                ('resources_used', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, help_text='Concise description of what kind of computations are required for the project on the cluster', max_length=512, null=True)),
                ('status', models.CharField(choices=[('INITIAL', 'INITIAL'), ('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED'), ('EXPIRED', 'EXPIRED')], default='INITIAL', help_text='Status of the project object', max_length=16)),
                ('gid', models.IntegerField(help_text='Id of the project on the cluster', null=True)),
                ('name', models.CharField(help_text='Name of the project on the cluster', max_length=64)),
                ('folders', models.JSONField(help_text='Paths to the folders of the project on the cluster')),
                ('expiration', models.DateTimeField(help_text='Expiration date of the project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcProjectInvitationEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Record UUID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='DateTime of last modification')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED')], default='PENDING', help_text='Status of the project invitation', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcProjectMembersEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcUserChangeRequestEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Record UUID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='DateTime of last modification')),
                ('status', models.CharField(choices=[('INITIAL', 'INITIAL'), ('ACTIVE', 'ACTIVE'), ('REVISION', 'REVISION'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('RETRACTED', 'RETRACTED'), ('ARCHIVED', 'ARCHIVED')], default='INITIAL', help_text='Status of the request', max_length=16)),
                ('comment', models.TextField(blank=True, help_text='This field is for communication between you and the HPC team.', null=True)),
                ('expiration', models.DateTimeField(help_text='Expiration date of the user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcUserCreateRequestEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Record UUID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='DateTime of last modification')),
                ('status', models.CharField(choices=[('INITIAL', 'INITIAL'), ('ACTIVE', 'ACTIVE'), ('REVISION', 'REVISION'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('RETRACTED', 'RETRACTED'), ('ARCHIVED', 'ARCHIVED')], default='INITIAL', help_text='Status of the request', max_length=16)),
                ('comment', models.TextField(blank=True, help_text='This field is for communication between you and the HPC team.', null=True)),
                ('resources_requested', models.JSONField()),
                ('email', models.EmailField(help_text='Email of user to send an invitation to', max_length=254)),
                ('expiration', models.DateTimeField(help_text='Expiration date of the user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcUserDeleteRequestEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Record UUID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='DateTime of last modification')),
                ('status', models.CharField(choices=[('INITIAL', 'INITIAL'), ('ACTIVE', 'ACTIVE'), ('REVISION', 'REVISION'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('RETRACTED', 'RETRACTED'), ('ARCHIVED', 'ARCHIVED')], default='INITIAL', help_text='Status of the request', max_length=16)),
                ('comment', models.TextField(blank=True, help_text='This field is for communication between you and the HPC team.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcUserEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Record UUID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='DateTime of creation')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='DateTime of last modification')),
                ('resources_requested', models.JSONField()),
                ('resources_used', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INITIAL', 'INITIAL'), ('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED'), ('EXPIRED', 'EXPIRED')], default='INITIAL', help_text='Status of the user object', max_length=16)),
                ('description', models.CharField(blank=True, help_text='Additional information about the user', max_length=512, null=True)),
                ('username', models.CharField(help_text='Username of the user on the cluster', max_length=32)),
                ('uid', models.IntegerField(help_text='Id of the user on the cluster', null=True)),
                ('expiration', models.DateTimeField(help_text='Expiration date of the user account')),
                ('home_directory', models.CharField(help_text='Path to the user home directory on the cluster', max_length=64)),
                ('login_shell', models.CharField(choices=[('/usr/bin/bash', '/usr/bin/bash'), ('/usr/bin/fish', '/usr/bin/fish'), ('/usr/bin/zsh', '/usr/bin/zsh'), ('/usr/bin/sh', '/usr/bin/sh')], default='/usr/bin/bash', help_text='Login shell of the user on the cluster', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HpcProjectChangeRequestMembers',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usersec.hpcprojectchangerequest_members',),
        ),
        migrations.CreateModel(
            name='HpcProjectCreateRequestMembers',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usersec.hpcprojectcreaterequest_members',),
        ),
        migrations.CreateModel(
            name='HpcProjectMembers',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usersec.hpcproject_members',),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcgroup',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcgroupevent" ("creator_id", "date_created", "date_modified", "delegate_id", "description", "expiration", "folders", "gid", "id", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "resources_requested", "resources_used", "status", "uuid") VALUES (NEW."creator_id", NEW."date_created", NEW."date_modified", NEW."delegate_id", NEW."description", NEW."expiration", NEW."folders", NEW."gid", NEW."id", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."resources_requested", NEW."resources_used", NEW."status", NEW."uuid"); RETURN NULL;', hash='54354bc05d94200ed4df5a9916b8df049d71622b', operation='INSERT', pgid='pgtrigger_insert_insert_a7614', table='usersec_hpcgroup', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcgroup',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."creator_id" IS DISTINCT FROM (NEW."creator_id") OR OLD."delegate_id" IS DISTINCT FROM (NEW."delegate_id") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."expiration" IS DISTINCT FROM (NEW."expiration") OR OLD."folders" IS DISTINCT FROM (NEW."folders") OR OLD."gid" IS DISTINCT FROM (NEW."gid") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."owner_id" IS DISTINCT FROM (NEW."owner_id") OR OLD."resources_requested" IS DISTINCT FROM (NEW."resources_requested") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "usersec_hpcgroupevent" ("creator_id", "date_created", "date_modified", "delegate_id", "description", "expiration", "folders", "gid", "id", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "resources_requested", "resources_used", "status", "uuid") VALUES (NEW."creator_id", NEW."date_created", NEW."date_modified", NEW."delegate_id", NEW."description", NEW."expiration", NEW."folders", NEW."gid", NEW."id", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."resources_requested", NEW."resources_used", NEW."status", NEW."uuid"); RETURN NULL;', hash='18a7859dda2f691a7d0fb57e795d28279846d774', operation='UPDATE', pgid='pgtrigger_update_update_3175b', table='usersec_hpcgroup', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcgroupchangerequest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcgroupchangerequestevent" ("comment", "date_created", "date_modified", "delegate_id", "description", "editor_id", "expiration", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requester_id", "resources_requested", "status", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."delegate_id", NEW."description", NEW."editor_id", NEW."expiration", NEW."group_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."requester_id", NEW."resources_requested", NEW."status", NEW."uuid"); RETURN NULL;', hash='b9ad28d0b03fcc5775da1c5ff764f472b2434b1b', operation='INSERT', pgid='pgtrigger_insert_insert_b64c2', table='usersec_hpcgroupchangerequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcgroupchangerequest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."comment" IS DISTINCT FROM (NEW."comment") OR OLD."delegate_id" IS DISTINCT FROM (NEW."delegate_id") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."editor_id" IS DISTINCT FROM (NEW."editor_id") OR OLD."expiration" IS DISTINCT FROM (NEW."expiration") OR OLD."group_id" IS DISTINCT FROM (NEW."group_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."requester_id" IS DISTINCT FROM (NEW."requester_id") OR OLD."resources_requested" IS DISTINCT FROM (NEW."resources_requested") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "usersec_hpcgroupchangerequestevent" ("comment", "date_created", "date_modified", "delegate_id", "description", "editor_id", "expiration", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requester_id", "resources_requested", "status", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."delegate_id", NEW."description", NEW."editor_id", NEW."expiration", NEW."group_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."requester_id", NEW."resources_requested", NEW."status", NEW."uuid"); RETURN NULL;', hash='509076cc8595b24355a7d31ce67c774f40ebba32', operation='UPDATE', pgid='pgtrigger_update_update_7b10e', table='usersec_hpcgroupchangerequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcgroupcreaterequest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcgroupcreaterequestevent" ("comment", "date_created", "date_modified", "description", "editor_id", "expiration", "folders", "group_id", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requester_id", "resources_requested", "status", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."description", NEW."editor_id", NEW."expiration", NEW."folders", NEW."group_id", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."requester_id", NEW."resources_requested", NEW."status", NEW."uuid"); RETURN NULL;', hash='04fdeca69c8e0bff9ab0abbb24d607aa6712cc52', operation='INSERT', pgid='pgtrigger_insert_insert_26a66', table='usersec_hpcgroupcreaterequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcgroupcreaterequest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."comment" IS DISTINCT FROM (NEW."comment") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."editor_id" IS DISTINCT FROM (NEW."editor_id") OR OLD."expiration" IS DISTINCT FROM (NEW."expiration") OR OLD."folders" IS DISTINCT FROM (NEW."folders") OR OLD."group_id" IS DISTINCT FROM (NEW."group_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."requester_id" IS DISTINCT FROM (NEW."requester_id") OR OLD."resources_requested" IS DISTINCT FROM (NEW."resources_requested") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "usersec_hpcgroupcreaterequestevent" ("comment", "date_created", "date_modified", "description", "editor_id", "expiration", "folders", "group_id", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requester_id", "resources_requested", "status", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."description", NEW."editor_id", NEW."expiration", NEW."folders", NEW."group_id", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."requester_id", NEW."resources_requested", NEW."status", NEW."uuid"); RETURN NULL;', hash='7a1d9726ed91dbb6ad8cf33c21d21aa697432489', operation='UPDATE', pgid='pgtrigger_update_update_3bedf', table='usersec_hpcgroupcreaterequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcgroupdeleterequest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcgroupdeleterequestevent" ("comment", "date_created", "date_modified", "editor_id", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requester_id", "status", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."editor_id", NEW."group_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."requester_id", NEW."status", NEW."uuid"); RETURN NULL;', hash='76aeba56f22087989327ee0211bfbb42e5730bb5', operation='INSERT', pgid='pgtrigger_insert_insert_075f5', table='usersec_hpcgroupdeleterequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcgroupdeleterequest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."comment" IS DISTINCT FROM (NEW."comment") OR OLD."editor_id" IS DISTINCT FROM (NEW."editor_id") OR OLD."group_id" IS DISTINCT FROM (NEW."group_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."requester_id" IS DISTINCT FROM (NEW."requester_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "usersec_hpcgroupdeleterequestevent" ("comment", "date_created", "date_modified", "editor_id", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requester_id", "status", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."editor_id", NEW."group_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."requester_id", NEW."status", NEW."uuid"); RETURN NULL;', hash='a7ce685b5f5f41c6a12f60937c423d24fc364364', operation='UPDATE', pgid='pgtrigger_update_update_fb54d', table='usersec_hpcgroupdeleterequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcgroupinvitation',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcgroupinvitationevent" ("date_created", "date_modified", "hpcusercreaterequest_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "username", "uuid") VALUES (NEW."date_created", NEW."date_modified", NEW."hpcusercreaterequest_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."username", NEW."uuid"); RETURN NULL;', hash='91ca90138033e87d7387afe3b20f7dd6895bccad', operation='INSERT', pgid='pgtrigger_insert_insert_ab1c8', table='usersec_hpcgroupinvitation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcgroupinvitation',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."hpcusercreaterequest_id" IS DISTINCT FROM (NEW."hpcusercreaterequest_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."username" IS DISTINCT FROM (NEW."username") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "usersec_hpcgroupinvitationevent" ("date_created", "date_modified", "hpcusercreaterequest_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "username", "uuid") VALUES (NEW."date_created", NEW."date_modified", NEW."hpcusercreaterequest_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."username", NEW."uuid"); RETURN NULL;', hash='d1e19454ca95644e222f8f1bd716207d6e7558dd', operation='UPDATE', pgid='pgtrigger_update_update_3787a', table='usersec_hpcgroupinvitation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcproject',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcprojectevent" ("creator_id", "date_created", "date_modified", "delegate_id", "description", "expiration", "folders", "gid", "group_id", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "resources_requested", "resources_used", "status", "uuid") VALUES (NEW."creator_id", NEW."date_created", NEW."date_modified", NEW."delegate_id", NEW."description", NEW."expiration", NEW."folders", NEW."gid", NEW."group_id", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."resources_requested", NEW."resources_used", NEW."status", NEW."uuid"); RETURN NULL;', hash='5f16702623f81f72a232121408165c70e5137588', operation='INSERT', pgid='pgtrigger_insert_insert_7b479', table='usersec_hpcproject', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcproject',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."creator_id" IS DISTINCT FROM (NEW."creator_id") OR OLD."delegate_id" IS DISTINCT FROM (NEW."delegate_id") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."expiration" IS DISTINCT FROM (NEW."expiration") OR OLD."folders" IS DISTINCT FROM (NEW."folders") OR OLD."gid" IS DISTINCT FROM (NEW."gid") OR OLD."group_id" IS DISTINCT FROM (NEW."group_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."resources_requested" IS DISTINCT FROM (NEW."resources_requested") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "usersec_hpcprojectevent" ("creator_id", "date_created", "date_modified", "delegate_id", "description", "expiration", "folders", "gid", "group_id", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "resources_requested", "resources_used", "status", "uuid") VALUES (NEW."creator_id", NEW."date_created", NEW."date_modified", NEW."delegate_id", NEW."description", NEW."expiration", NEW."folders", NEW."gid", NEW."group_id", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."resources_requested", NEW."resources_used", NEW."status", NEW."uuid"); RETURN NULL;', hash='09aee5d05e309464ab7d12144453ec3fe0b9c4c2', operation='UPDATE', pgid='pgtrigger_update_update_ef7dd', table='usersec_hpcproject', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcprojectchangerequest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcprojectchangerequestevent" ("comment", "date_created", "date_modified", "delegate_id", "description", "editor_id", "expiration", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "project_id", "requester_id", "resources_requested", "status", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."delegate_id", NEW."description", NEW."editor_id", NEW."expiration", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."project_id", NEW."requester_id", NEW."resources_requested", NEW."status", NEW."uuid"); RETURN NULL;', hash='abba2cdc9a786a9d7ca9123a962608b7d7a81f2b', operation='INSERT', pgid='pgtrigger_insert_insert_cd218', table='usersec_hpcprojectchangerequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcprojectchangerequest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."comment" IS DISTINCT FROM (NEW."comment") OR OLD."delegate_id" IS DISTINCT FROM (NEW."delegate_id") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."editor_id" IS DISTINCT FROM (NEW."editor_id") OR OLD."expiration" IS DISTINCT FROM (NEW."expiration") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."project_id" IS DISTINCT FROM (NEW."project_id") OR OLD."requester_id" IS DISTINCT FROM (NEW."requester_id") OR OLD."resources_requested" IS DISTINCT FROM (NEW."resources_requested") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "usersec_hpcprojectchangerequestevent" ("comment", "date_created", "date_modified", "delegate_id", "description", "editor_id", "expiration", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "project_id", "requester_id", "resources_requested", "status", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."delegate_id", NEW."description", NEW."editor_id", NEW."expiration", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."project_id", NEW."requester_id", NEW."resources_requested", NEW."status", NEW."uuid"); RETURN NULL;', hash='a063e5739cbc99850b266a336ed13ef2d82fb61e', operation='UPDATE', pgid='pgtrigger_update_update_13a1f', table='usersec_hpcprojectchangerequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcprojectcreaterequest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcprojectcreaterequestevent" ("comment", "date_created", "date_modified", "delegate_id", "description", "editor_id", "expiration", "folders", "group_id", "id", "name", "name_requested", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "project_id", "requester_id", "resources_requested", "status", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."delegate_id", NEW."description", NEW."editor_id", NEW."expiration", NEW."folders", NEW."group_id", NEW."id", NEW."name", NEW."name_requested", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."project_id", NEW."requester_id", NEW."resources_requested", NEW."status", NEW."uuid"); RETURN NULL;', hash='07b09aae58f2b7638e21cb5874935e5dd21d72b4', operation='INSERT', pgid='pgtrigger_insert_insert_e5a81', table='usersec_hpcprojectcreaterequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcprojectcreaterequest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."comment" IS DISTINCT FROM (NEW."comment") OR OLD."delegate_id" IS DISTINCT FROM (NEW."delegate_id") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."editor_id" IS DISTINCT FROM (NEW."editor_id") OR OLD."expiration" IS DISTINCT FROM (NEW."expiration") OR OLD."folders" IS DISTINCT FROM (NEW."folders") OR OLD."group_id" IS DISTINCT FROM (NEW."group_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."name" IS DISTINCT FROM (NEW."name") OR OLD."name_requested" IS DISTINCT FROM (NEW."name_requested") OR OLD."project_id" IS DISTINCT FROM (NEW."project_id") OR OLD."requester_id" IS DISTINCT FROM (NEW."requester_id") OR OLD."resources_requested" IS DISTINCT FROM (NEW."resources_requested") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "usersec_hpcprojectcreaterequestevent" ("comment", "date_created", "date_modified", "delegate_id", "description", "editor_id", "expiration", "folders", "group_id", "id", "name", "name_requested", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "project_id", "requester_id", "resources_requested", "status", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."delegate_id", NEW."description", NEW."editor_id", NEW."expiration", NEW."folders", NEW."group_id", NEW."id", NEW."name", NEW."name_requested", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."project_id", NEW."requester_id", NEW."resources_requested", NEW."status", NEW."uuid"); RETURN NULL;', hash='48e9bdfd7da34605623f6df6149c637d0f19db43', operation='UPDATE', pgid='pgtrigger_update_update_031d9', table='usersec_hpcprojectcreaterequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcprojectdeleterequest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcprojectdeleterequestevent" ("comment", "date_created", "date_modified", "editor_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "project_id", "requester_id", "status", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."editor_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."project_id", NEW."requester_id", NEW."status", NEW."uuid"); RETURN NULL;', hash='42b1f77f3f675720506056d331cbbb175f44fe6f', operation='INSERT', pgid='pgtrigger_insert_insert_c4970', table='usersec_hpcprojectdeleterequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcprojectdeleterequest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."comment" IS DISTINCT FROM (NEW."comment") OR OLD."editor_id" IS DISTINCT FROM (NEW."editor_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."project_id" IS DISTINCT FROM (NEW."project_id") OR OLD."requester_id" IS DISTINCT FROM (NEW."requester_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "usersec_hpcprojectdeleterequestevent" ("comment", "date_created", "date_modified", "editor_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "project_id", "requester_id", "status", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."editor_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."project_id", NEW."requester_id", NEW."status", NEW."uuid"); RETURN NULL;', hash='446d5f7e3baad7912db87c866b30e66b9a23d8aa', operation='UPDATE', pgid='pgtrigger_update_update_85b4d', table='usersec_hpcprojectdeleterequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcprojectinvitation',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcprojectinvitationevent" ("date_created", "date_modified", "hpcprojectchangerequest_id", "hpcprojectcreaterequest_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "project_id", "status", "user_id", "uuid") VALUES (NEW."date_created", NEW."date_modified", NEW."hpcprojectchangerequest_id", NEW."hpcprojectcreaterequest_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."project_id", NEW."status", NEW."user_id", NEW."uuid"); RETURN NULL;', hash='f61b99a3b64ae1424941138b6155c1c1e78bba6e', operation='INSERT', pgid='pgtrigger_insert_insert_e661c', table='usersec_hpcprojectinvitation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcprojectinvitation',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."hpcprojectchangerequest_id" IS DISTINCT FROM (NEW."hpcprojectchangerequest_id") OR OLD."hpcprojectcreaterequest_id" IS DISTINCT FROM (NEW."hpcprojectcreaterequest_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."project_id" IS DISTINCT FROM (NEW."project_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "usersec_hpcprojectinvitationevent" ("date_created", "date_modified", "hpcprojectchangerequest_id", "hpcprojectcreaterequest_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "project_id", "status", "user_id", "uuid") VALUES (NEW."date_created", NEW."date_modified", NEW."hpcprojectchangerequest_id", NEW."hpcprojectcreaterequest_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."project_id", NEW."status", NEW."user_id", NEW."uuid"); RETURN NULL;', hash='dad5952c96c4ddcbea9fd68d66b34ca59a76ce86', operation='UPDATE', pgid='pgtrigger_update_update_41b3e', table='usersec_hpcprojectinvitation', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcuser',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcuserevent" ("creator_id", "date_created", "date_modified", "description", "expiration", "home_directory", "id", "login_shell", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "primary_group_id", "resources_requested", "resources_used", "status", "uid", "user_id", "username", "uuid") VALUES (NEW."creator_id", NEW."date_created", NEW."date_modified", NEW."description", NEW."expiration", NEW."home_directory", NEW."id", NEW."login_shell", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."primary_group_id", NEW."resources_requested", NEW."resources_used", NEW."status", NEW."uid", NEW."user_id", NEW."username", NEW."uuid"); RETURN NULL;', hash='36544273b2d38294cde687b3ecc139716c57aa12', operation='INSERT', pgid='pgtrigger_insert_insert_1c81c', table='usersec_hpcuser', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcuser',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."creator_id" IS DISTINCT FROM (NEW."creator_id") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."expiration" IS DISTINCT FROM (NEW."expiration") OR OLD."home_directory" IS DISTINCT FROM (NEW."home_directory") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."login_shell" IS DISTINCT FROM (NEW."login_shell") OR OLD."primary_group_id" IS DISTINCT FROM (NEW."primary_group_id") OR OLD."resources_requested" IS DISTINCT FROM (NEW."resources_requested") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."uid" IS DISTINCT FROM (NEW."uid") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."username" IS DISTINCT FROM (NEW."username") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "usersec_hpcuserevent" ("creator_id", "date_created", "date_modified", "description", "expiration", "home_directory", "id", "login_shell", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "primary_group_id", "resources_requested", "resources_used", "status", "uid", "user_id", "username", "uuid") VALUES (NEW."creator_id", NEW."date_created", NEW."date_modified", NEW."description", NEW."expiration", NEW."home_directory", NEW."id", NEW."login_shell", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."primary_group_id", NEW."resources_requested", NEW."resources_used", NEW."status", NEW."uid", NEW."user_id", NEW."username", NEW."uuid"); RETURN NULL;', hash='d36578ef69b83a1054e2b0d30f3bb326f0cdf447', operation='UPDATE', pgid='pgtrigger_update_update_24135', table='usersec_hpcuser', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcuserchangerequest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcuserchangerequestevent" ("comment", "date_created", "date_modified", "editor_id", "expiration", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requester_id", "status", "user_id", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."editor_id", NEW."expiration", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."requester_id", NEW."status", NEW."user_id", NEW."uuid"); RETURN NULL;', hash='0a3a8ce0c458dd32a1a41b3479371ba8c2178243', operation='INSERT', pgid='pgtrigger_insert_insert_74aa5', table='usersec_hpcuserchangerequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcuserchangerequest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."comment" IS DISTINCT FROM (NEW."comment") OR OLD."editor_id" IS DISTINCT FROM (NEW."editor_id") OR OLD."expiration" IS DISTINCT FROM (NEW."expiration") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."requester_id" IS DISTINCT FROM (NEW."requester_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "usersec_hpcuserchangerequestevent" ("comment", "date_created", "date_modified", "editor_id", "expiration", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requester_id", "status", "user_id", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."editor_id", NEW."expiration", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."requester_id", NEW."status", NEW."user_id", NEW."uuid"); RETURN NULL;', hash='d47303ee002ecb426fd33919ab09147a9683c742', operation='UPDATE', pgid='pgtrigger_update_update_c1ba5', table='usersec_hpcuserchangerequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcusercreaterequest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcusercreaterequestevent" ("comment", "date_created", "date_modified", "editor_id", "email", "expiration", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requester_id", "resources_requested", "status", "user_id", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."editor_id", NEW."email", NEW."expiration", NEW."group_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."requester_id", NEW."resources_requested", NEW."status", NEW."user_id", NEW."uuid"); RETURN NULL;', hash='f811371f65f9eaae559e0ad4cc6962721a702ab9', operation='INSERT', pgid='pgtrigger_insert_insert_e4758', table='usersec_hpcusercreaterequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcusercreaterequest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."comment" IS DISTINCT FROM (NEW."comment") OR OLD."editor_id" IS DISTINCT FROM (NEW."editor_id") OR OLD."email" IS DISTINCT FROM (NEW."email") OR OLD."expiration" IS DISTINCT FROM (NEW."expiration") OR OLD."group_id" IS DISTINCT FROM (NEW."group_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."requester_id" IS DISTINCT FROM (NEW."requester_id") OR OLD."resources_requested" IS DISTINCT FROM (NEW."resources_requested") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "usersec_hpcusercreaterequestevent" ("comment", "date_created", "date_modified", "editor_id", "email", "expiration", "group_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requester_id", "resources_requested", "status", "user_id", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."editor_id", NEW."email", NEW."expiration", NEW."group_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."requester_id", NEW."resources_requested", NEW."status", NEW."user_id", NEW."uuid"); RETURN NULL;', hash='cca5913b958bcba8a9e6b3b47ec7cd30c4a36b65', operation='UPDATE', pgid='pgtrigger_update_update_fce6d', table='usersec_hpcusercreaterequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcuserdeleterequest',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcuserdeleterequestevent" ("comment", "date_created", "date_modified", "editor_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requester_id", "status", "user_id", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."editor_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."requester_id", NEW."status", NEW."user_id", NEW."uuid"); RETURN NULL;', hash='354f91debd696082f343125f09938a2b3b223c5b', operation='INSERT', pgid='pgtrigger_insert_insert_05e19', table='usersec_hpcuserdeleterequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcuserdeleterequest',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."comment" IS DISTINCT FROM (NEW."comment") OR OLD."editor_id" IS DISTINCT FROM (NEW."editor_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."requester_id" IS DISTINCT FROM (NEW."requester_id") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."uuid" IS DISTINCT FROM (NEW."uuid"))', func='INSERT INTO "usersec_hpcuserdeleterequestevent" ("comment", "date_created", "date_modified", "editor_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "requester_id", "status", "user_id", "uuid") VALUES (NEW."comment", NEW."date_created", NEW."date_modified", NEW."editor_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."requester_id", NEW."status", NEW."user_id", NEW."uuid"); RETURN NULL;', hash='b90b5bfb20134a2798cc212a4ab1f092f3ad7188', operation='UPDATE', pgid='pgtrigger_update_update_b49e3', table='usersec_hpcuserdeleterequest', when='AFTER')),
        ),
        migrations.AddField(
            model_name='hpcuserevent',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='User creating the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcuserevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcuserevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='usersec.hpcuser'),
        ),
        migrations.AddField(
            model_name='hpcuserevent',
            name='primary_group',
            field=models.ForeignKey(db_constraint=False, help_text='Primary group the user belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcgroup'),
        ),
        migrations.AddField(
            model_name='hpcuserevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, help_text='Associated Django user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcuserdeleterequestevent',
            name='editor',
            field=models.ForeignKey(db_constraint=False, help_text='User editing the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcuserdeleterequestevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcuserdeleterequestevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='usersec.hpcuserdeleterequest'),
        ),
        migrations.AddField(
            model_name='hpcuserdeleterequestevent',
            name='requester',
            field=models.ForeignKey(db_constraint=False, help_text='User creating the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcuserdeleterequestevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, help_text='User the request belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcuser'),
        ),
        migrations.AddField(
            model_name='hpcusercreaterequestevent',
            name='editor',
            field=models.ForeignKey(db_constraint=False, help_text='User editing the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcusercreaterequestevent',
            name='group',
            field=models.ForeignKey(db_constraint=False, help_text='Group the request belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcgroup'),
        ),
        migrations.AddField(
            model_name='hpcusercreaterequestevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcusercreaterequestevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='usersec.hpcusercreaterequest'),
        ),
        migrations.AddField(
            model_name='hpcusercreaterequestevent',
            name='requester',
            field=models.ForeignKey(db_constraint=False, help_text='User creating the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcusercreaterequestevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, help_text='User the request belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcuser'),
        ),
        migrations.AddField(
            model_name='hpcuserchangerequestevent',
            name='editor',
            field=models.ForeignKey(db_constraint=False, help_text='User editing the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcuserchangerequestevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcuserchangerequestevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='usersec.hpcuserchangerequest'),
        ),
        migrations.AddField(
            model_name='hpcuserchangerequestevent',
            name='requester',
            field=models.ForeignKey(db_constraint=False, help_text='User creating the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcuserchangerequestevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, help_text='User the request belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcuser'),
        ),
        migrations.AddField(
            model_name='hpcprojectmembersevent',
            name='hpcproject',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcproject'),
        ),
        migrations.AddField(
            model_name='hpcprojectmembersevent',
            name='hpcuser',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcuser'),
        ),
        migrations.AddField(
            model_name='hpcprojectmembersevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcprojectinvitationevent',
            name='hpcprojectchangerequest',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Project change request that initiated the invitation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcprojectchangerequest'),
        ),
        migrations.AddField(
            model_name='hpcprojectinvitationevent',
            name='hpcprojectcreaterequest',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Project create request that initiated the invitation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcprojectcreaterequest'),
        ),
        migrations.AddField(
            model_name='hpcprojectinvitationevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcprojectinvitationevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='usersec.hpcprojectinvitation'),
        ),
        migrations.AddField(
            model_name='hpcprojectinvitationevent',
            name='project',
            field=models.ForeignKey(db_constraint=False, help_text='Project the user has been invited to', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcproject'),
        ),
        migrations.AddField(
            model_name='hpcprojectinvitationevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, help_text='Invited user', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcuser'),
        ),
        migrations.AddField(
            model_name='hpcprojectevent',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='User creating the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcprojectevent',
            name='delegate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The optional delegate can act on behalf of the project owner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcuser'),
        ),
        migrations.AddField(
            model_name='hpcprojectevent',
            name='group',
            field=models.ForeignKey(db_constraint=False, help_text='Group that requested project. Group PI is owner of project', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcgroup'),
        ),
        migrations.AddField(
            model_name='hpcprojectevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcprojectevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='usersec.hpcproject'),
        ),
        migrations.AddField(
            model_name='hpcprojectdeleterequestevent',
            name='editor',
            field=models.ForeignKey(db_constraint=False, help_text='User editing the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcprojectdeleterequestevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcprojectdeleterequestevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='usersec.hpcprojectdeleterequest'),
        ),
        migrations.AddField(
            model_name='hpcprojectdeleterequestevent',
            name='project',
            field=models.ForeignKey(db_constraint=False, help_text='Project the request belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcproject'),
        ),
        migrations.AddField(
            model_name='hpcprojectdeleterequestevent',
            name='requester',
            field=models.ForeignKey(db_constraint=False, help_text='User creating the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcprojectcreaterequestmembersevent',
            name='hpcprojectcreaterequest',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcprojectcreaterequest'),
        ),
        migrations.AddField(
            model_name='hpcprojectcreaterequestmembersevent',
            name='hpcuser',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcuser'),
        ),
        migrations.AddField(
            model_name='hpcprojectcreaterequestmembersevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcprojectcreaterequestevent',
            name='delegate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The optional delegate can act on behalf of the project owner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcuser'),
        ),
        migrations.AddField(
            model_name='hpcprojectcreaterequestevent',
            name='editor',
            field=models.ForeignKey(db_constraint=False, help_text='User editing the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcprojectcreaterequestevent',
            name='group',
            field=models.ForeignKey(db_constraint=False, help_text='Group the request belongs to', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcgroup'),
        ),
        migrations.AddField(
            model_name='hpcprojectcreaterequestevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcprojectcreaterequestevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='usersec.hpcprojectcreaterequest'),
        ),
        migrations.AddField(
            model_name='hpcprojectcreaterequestevent',
            name='project',
            field=models.ForeignKey(db_constraint=False, help_text='Project the request belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcproject'),
        ),
        migrations.AddField(
            model_name='hpcprojectcreaterequestevent',
            name='requester',
            field=models.ForeignKey(db_constraint=False, help_text='User creating the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcprojectchangerequestmembersevent',
            name='hpcprojectchangerequest',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcprojectchangerequest'),
        ),
        migrations.AddField(
            model_name='hpcprojectchangerequestmembersevent',
            name='hpcuser',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcuser'),
        ),
        migrations.AddField(
            model_name='hpcprojectchangerequestmembersevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcprojectchangerequestevent',
            name='delegate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The optional delegate can act on behalf of the project owner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcuser'),
        ),
        migrations.AddField(
            model_name='hpcprojectchangerequestevent',
            name='editor',
            field=models.ForeignKey(db_constraint=False, help_text='User editing the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcprojectchangerequestevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcprojectchangerequestevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='usersec.hpcprojectchangerequest'),
        ),
        migrations.AddField(
            model_name='hpcprojectchangerequestevent',
            name='project',
            field=models.ForeignKey(db_constraint=False, help_text='Project the request belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcproject'),
        ),
        migrations.AddField(
            model_name='hpcprojectchangerequestevent',
            name='requester',
            field=models.ForeignKey(db_constraint=False, help_text='User creating the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcgroupinvitationevent',
            name='hpcusercreaterequest',
            field=models.ForeignKey(db_constraint=False, help_text='User create request that initiated the invitation', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcusercreaterequest'),
        ),
        migrations.AddField(
            model_name='hpcgroupinvitationevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcgroupinvitationevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='usersec.hpcgroupinvitation'),
        ),
        migrations.AddField(
            model_name='hpcgroupevent',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='User creating the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcgroupevent',
            name='delegate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The optional delegate can act on behalf of the project owner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcuser'),
        ),
        migrations.AddField(
            model_name='hpcgroupevent',
            name='owner',
            field=models.ForeignKey(db_constraint=False, help_text='User registered as owner of the group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcuser'),
        ),
        migrations.AddField(
            model_name='hpcgroupevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcgroupevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='usersec.hpcgroup'),
        ),
        migrations.AddField(
            model_name='hpcgroupdeleterequestevent',
            name='editor',
            field=models.ForeignKey(db_constraint=False, help_text='User editing the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcgroupdeleterequestevent',
            name='group',
            field=models.ForeignKey(db_constraint=False, help_text='Group the request belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcgroup'),
        ),
        migrations.AddField(
            model_name='hpcgroupdeleterequestevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcgroupdeleterequestevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='usersec.hpcgroupdeleterequest'),
        ),
        migrations.AddField(
            model_name='hpcgroupdeleterequestevent',
            name='requester',
            field=models.ForeignKey(db_constraint=False, help_text='User creating the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcgroupcreaterequestevent',
            name='editor',
            field=models.ForeignKey(db_constraint=False, help_text='User editing the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcgroupcreaterequestevent',
            name='group',
            field=models.ForeignKey(db_constraint=False, help_text='Group the request belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcgroup'),
        ),
        migrations.AddField(
            model_name='hpcgroupcreaterequestevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcgroupcreaterequestevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='usersec.hpcgroupcreaterequest'),
        ),
        migrations.AddField(
            model_name='hpcgroupcreaterequestevent',
            name='requester',
            field=models.ForeignKey(db_constraint=False, help_text='User creating the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcgroupchangerequestevent',
            name='delegate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The optional delegate can act on behalf of the group owner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcuser'),
        ),
        migrations.AddField(
            model_name='hpcgroupchangerequestevent',
            name='editor',
            field=models.ForeignKey(db_constraint=False, help_text='User editing the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hpcgroupchangerequestevent',
            name='group',
            field=models.ForeignKey(db_constraint=False, help_text='Group the request belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='usersec.hpcgroup'),
        ),
        migrations.AddField(
            model_name='hpcgroupchangerequestevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hpcgroupchangerequestevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='usersec.hpcgroupchangerequest'),
        ),
        migrations.AddField(
            model_name='hpcgroupchangerequestevent',
            name='requester',
            field=models.ForeignKey(db_constraint=False, help_text='User creating the request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcprojectchangerequestmembers',
            trigger=pgtrigger.compiler.Trigger(name='members_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcprojectchangerequestmembersevent" ("hpcprojectchangerequest_id", "hpcuser_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (NEW."hpcprojectchangerequest_id", NEW."hpcuser_id", NEW."id", _pgh_attach_context(), NOW(), \'members.add\'); RETURN NULL;', hash='18131f79052cf010a9bbe8017b18764622d1d147', operation='INSERT', pgid='pgtrigger_members_add_insert_b33b3', table='usersec_hpcprojectchangerequest_members', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcprojectchangerequestmembers',
            trigger=pgtrigger.compiler.Trigger(name='members_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcprojectchangerequestmembersevent" ("hpcprojectchangerequest_id", "hpcuser_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (OLD."hpcprojectchangerequest_id", OLD."hpcuser_id", OLD."id", _pgh_attach_context(), NOW(), \'members.remove\'); RETURN NULL;', hash='53847d99e67dd9ff8f2af6cf9f89bdeab1567e65', operation='DELETE', pgid='pgtrigger_members_remove_delete_cf54a', table='usersec_hpcprojectchangerequest_members', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcprojectcreaterequestmembers',
            trigger=pgtrigger.compiler.Trigger(name='members_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcprojectcreaterequestmembersevent" ("hpcprojectcreaterequest_id", "hpcuser_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (NEW."hpcprojectcreaterequest_id", NEW."hpcuser_id", NEW."id", _pgh_attach_context(), NOW(), \'members.add\'); RETURN NULL;', hash='918810acaf493489ddf3f93f8fd8bd44a10cba9f', operation='INSERT', pgid='pgtrigger_members_add_insert_99ca9', table='usersec_hpcprojectcreaterequest_members', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcprojectcreaterequestmembers',
            trigger=pgtrigger.compiler.Trigger(name='members_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcprojectcreaterequestmembersevent" ("hpcprojectcreaterequest_id", "hpcuser_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (OLD."hpcprojectcreaterequest_id", OLD."hpcuser_id", OLD."id", _pgh_attach_context(), NOW(), \'members.remove\'); RETURN NULL;', hash='a0b97277ad55fb815e912c8a0aea4819928a1af4', operation='DELETE', pgid='pgtrigger_members_remove_delete_a49ba', table='usersec_hpcprojectcreaterequest_members', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcprojectmembers',
            trigger=pgtrigger.compiler.Trigger(name='members_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcprojectmembersevent" ("hpcproject_id", "hpcuser_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (NEW."hpcproject_id", NEW."hpcuser_id", NEW."id", _pgh_attach_context(), NOW(), \'members.add\'); RETURN NULL;', hash='10d4c3da6d8c3e3cd6fef19b9fb49866b2c5a3e3', operation='INSERT', pgid='pgtrigger_members_add_insert_b9959', table='usersec_hpcproject_members', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hpcprojectmembers',
            trigger=pgtrigger.compiler.Trigger(name='members_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "usersec_hpcprojectmembersevent" ("hpcproject_id", "hpcuser_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label") VALUES (OLD."hpcproject_id", OLD."hpcuser_id", OLD."id", _pgh_attach_context(), NOW(), \'members.remove\'); RETURN NULL;', hash='0ec82e1f17f5e5d3b94fa873b22a607bbb9681af', operation='DELETE', pgid='pgtrigger_members_remove_delete_cf56b', table='usersec_hpcproject_members', when='AFTER')),
        ),
    ]
