from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usersec", "0033_backfill_history"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hpcgroupchangerequestversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hpcgroupchangerequestversion',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='hpcgroupchangerequestversion',
            name='delegate',
        ),
        migrations.RemoveField(
            model_name='hpcgroupchangerequestversion',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='hpcgroupchangerequestversion',
            name='group',
        ),
        migrations.RemoveField(
            model_name='hpcgroupchangerequestversion',
            name='requester',
        ),
        migrations.AlterUniqueTogether(
            name='hpcgroupcreaterequestversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hpcgroupcreaterequestversion',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='hpcgroupcreaterequestversion',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='hpcgroupcreaterequestversion',
            name='group',
        ),
        migrations.RemoveField(
            model_name='hpcgroupcreaterequestversion',
            name='requester',
        ),
        migrations.AlterUniqueTogether(
            name='hpcgroupdeleterequestversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hpcgroupdeleterequestversion',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='hpcgroupdeleterequestversion',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='hpcgroupdeleterequestversion',
            name='group',
        ),
        migrations.RemoveField(
            model_name='hpcgroupdeleterequestversion',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='hpcgroupinvitationversion',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='hpcgroupinvitationversion',
            name='hpcusercreaterequest',
        ),
        migrations.AlterUniqueTogether(
            name='hpcgroupversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hpcgroupversion',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='hpcgroupversion',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='hpcgroupversion',
            name='delegate',
        ),
        migrations.RemoveField(
            model_name='hpcgroupversion',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='hpcprojectchangerequestversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hpcprojectchangerequestversion',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='hpcprojectchangerequestversion',
            name='delegate',
        ),
        migrations.RemoveField(
            model_name='hpcprojectchangerequestversion',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='hpcprojectchangerequestversion',
            name='members',
        ),
        migrations.RemoveField(
            model_name='hpcprojectchangerequestversion',
            name='project',
        ),
        migrations.RemoveField(
            model_name='hpcprojectchangerequestversion',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='hpcprojectcreaterequestversion',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='hpcprojectcreaterequestversion',
            name='delegate',
        ),
        migrations.RemoveField(
            model_name='hpcprojectcreaterequestversion',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='hpcprojectcreaterequestversion',
            name='group',
        ),
        migrations.RemoveField(
            model_name='hpcprojectcreaterequestversion',
            name='members',
        ),
        migrations.RemoveField(
            model_name='hpcprojectcreaterequestversion',
            name='project',
        ),
        migrations.RemoveField(
            model_name='hpcprojectcreaterequestversion',
            name='requester',
        ),
        migrations.AlterUniqueTogether(
            name='hpcprojectdeleterequestversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hpcprojectdeleterequestversion',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='hpcprojectdeleterequestversion',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='hpcprojectdeleterequestversion',
            name='project',
        ),
        migrations.RemoveField(
            model_name='hpcprojectdeleterequestversion',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='hpcprojectinvitationversion',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='hpcprojectinvitationversion',
            name='hpcprojectchangerequest',
        ),
        migrations.RemoveField(
            model_name='hpcprojectinvitationversion',
            name='hpcprojectcreaterequest',
        ),
        migrations.RemoveField(
            model_name='hpcprojectinvitationversion',
            name='project',
        ),
        migrations.RemoveField(
            model_name='hpcprojectinvitationversion',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='hpcprojectversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hpcprojectversion',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='hpcprojectversion',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='hpcprojectversion',
            name='delegate',
        ),
        migrations.RemoveField(
            model_name='hpcprojectversion',
            name='group',
        ),
        migrations.RemoveField(
            model_name='hpcprojectversion',
            name='members',
        ),
        migrations.AlterUniqueTogether(
            name='hpcuserchangerequestversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hpcuserchangerequestversion',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='hpcuserchangerequestversion',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='hpcuserchangerequestversion',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='hpcuserchangerequestversion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hpcusercreaterequestversion',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='hpcusercreaterequestversion',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='hpcusercreaterequestversion',
            name='group',
        ),
        migrations.RemoveField(
            model_name='hpcusercreaterequestversion',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='hpcusercreaterequestversion',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='hpcuserdeleterequestversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hpcuserdeleterequestversion',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='hpcuserdeleterequestversion',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='hpcuserdeleterequestversion',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='hpcuserdeleterequestversion',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='hpcuserversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hpcuserversion',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='hpcuserversion',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='hpcuserversion',
            name='primary_group',
        ),
        migrations.RemoveField(
            model_name='hpcuserversion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hpcgroup',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='hpcgroupchangerequest',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='hpcgroupcreaterequest',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='hpcgroupdeleterequest',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='hpcgroupinvitation',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='hpcproject',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='hpcprojectchangerequest',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='hpcprojectcreaterequest',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='hpcprojectdeleterequest',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='hpcprojectinvitation',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='hpcuser',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='hpcuserchangerequest',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='hpcusercreaterequest',
            name='current_version',
        ),
        migrations.RemoveField(
            model_name='hpcuserdeleterequest',
            name='current_version',
        ),
        migrations.DeleteModel(
            name='HpcGroupChangeRequestVersion',
        ),
        migrations.DeleteModel(
            name='HpcGroupCreateRequestVersion',
        ),
        migrations.DeleteModel(
            name='HpcGroupDeleteRequestVersion',
        ),
        migrations.DeleteModel(
            name='HpcGroupInvitationVersion',
        ),
        migrations.DeleteModel(
            name='HpcGroupVersion',
        ),
        migrations.DeleteModel(
            name='HpcProjectChangeRequestVersion',
        ),
        migrations.DeleteModel(
            name='HpcProjectCreateRequestVersion',
        ),
        migrations.DeleteModel(
            name='HpcProjectDeleteRequestVersion',
        ),
        migrations.DeleteModel(
            name='HpcProjectInvitationVersion',
        ),
        migrations.DeleteModel(
            name='HpcProjectVersion',
        ),
        migrations.DeleteModel(
            name='HpcUserChangeRequestVersion',
        ),
        migrations.DeleteModel(
            name='HpcUserCreateRequestVersion',
        ),
        migrations.DeleteModel(
            name='HpcUserDeleteRequestVersion',
        ),
        migrations.DeleteModel(
            name='HpcUserVersion',
        ),
    ]
