name: Feature Request
description: File a feature request
labels: ["enhancement"]
assignees:
  - stolpeo
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature-request
    attributes:
      label: What is your feature request?
      description: Also tell us why you think this is useful for you.
      placeholder: Tell us what you wish for!
    validations:
      required: true
