name: Feature Request
description: File a feature request
title: "[feat] "
labels: ["feature"]
assignees:
  - stolpeo
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature-request
    attributes:
      label: What is your feature request?
      description: Also tell us why you think this is useful for you.
      placeholder: Tell us what you wish for!
      value: "I need that feature!"
    validations:
      required: true
  - type: textarea
    id: similar-feature
    attributes:
      label: Have you seen anything similar somewhere else?
      description: Post a link or describe it.
      placeholder: Tell us what you've seen!
      value: "They did a similar thing!"
    validations:
      required: true
