# Generated by Django 4.0.3 on 2022-03-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_hpcadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="Phone number of User"),
        ),
    ]
