# Generated by Django 4.2.10 on 2024-02-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uid",
            field=models.IntegerField(blank=True, null=True, verbose_name="UID of User"),
        ),
    ]
