# Generated by Django 4.0.2 on 2022-03-21 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usersec", "0002_hpcgroup_adjustments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hpcgroupcreaterequest",
            name="delegate",
        ),
        migrations.RemoveField(
            model_name="hpcuserchangerequest",
            name="group",
        ),
        migrations.RemoveField(
            model_name="hpcusercreaterequest",
            name="group",
        ),
        migrations.RemoveField(
            model_name="hpcusercreaterequestversion",
            name="group",
        ),
        migrations.RemoveField(
            model_name="hpcuserdeleterequest",
            name="group",
        ),
        migrations.AddField(
            model_name="hpcgroupchangerequestversion",
            name="belongs_to",
            field=models.ForeignKey(
                help_text="Object this version belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version_history",
                to="usersec.hpcgroupchangerequest",
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupcreaterequest",
            name="delegate_email",
            field=models.CharField(
                blank=True,
                help_text="Email address of the delegate",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupcreaterequest",
            name="member_emails",
            field=models.TextField(
                blank=True,
                help_text="Email addresses of the group members, comma separated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupcreaterequestversion",
            name="belongs_to",
            field=models.ForeignKey(
                help_text="Object this version belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version_history",
                to="usersec.hpcgroupcreaterequest",
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupcreaterequestversion",
            name="delegate_email",
            field=models.CharField(
                blank=True,
                help_text="Email address of the delegate",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupcreaterequestversion",
            name="member_emails",
            field=models.TextField(
                blank=True,
                help_text="Email addresses of the group members, comma separated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupdeleterequestversion",
            name="belongs_to",
            field=models.ForeignKey(
                help_text="Object this version belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version_history",
                to="usersec.hpcgroupdeleterequest",
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupversion",
            name="belongs_to",
            field=models.ForeignKey(
                help_text="Object this version belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version_history",
                to="usersec.hpcgroup",
            ),
        ),
        migrations.AddField(
            model_name="hpcuserchangerequest",
            name="user",
            field=models.ForeignKey(
                help_text="User the request belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AddField(
            model_name="hpcuserchangerequestversion",
            name="belongs_to",
            field=models.ForeignKey(
                help_text="Object this version belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version_history",
                to="usersec.hpcuserchangerequest",
            ),
        ),
        migrations.AddField(
            model_name="hpcuserchangerequestversion",
            name="user",
            field=models.ForeignKey(
                help_text="User the request belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AddField(
            model_name="hpcusercreaterequest",
            name="user",
            field=models.ForeignKey(
                help_text="User the request belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AddField(
            model_name="hpcusercreaterequestversion",
            name="belongs_to",
            field=models.ForeignKey(
                help_text="Object this version belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version_history",
                to="usersec.hpcusercreaterequest",
            ),
        ),
        migrations.AddField(
            model_name="hpcusercreaterequestversion",
            name="user",
            field=models.ForeignKey(
                help_text="User the request belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AddField(
            model_name="hpcuserdeleterequest",
            name="user",
            field=models.ForeignKey(
                help_text="User the request belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AddField(
            model_name="hpcuserdeleterequestversion",
            name="belongs_to",
            field=models.ForeignKey(
                help_text="Object this version belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version_history",
                to="usersec.hpcuserdeleterequest",
            ),
        ),
        migrations.AddField(
            model_name="hpcuserdeleterequestversion",
            name="user",
            field=models.ForeignKey(
                help_text="User the request belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AddField(
            model_name="hpcuserversion",
            name="belongs_to",
            field=models.ForeignKey(
                help_text="Object this version belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version_history",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroup",
            name="folder",
            field=models.CharField(
                help_text="Path to the group folder on the cluster",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroup",
            name="name",
            field=models.CharField(help_text="Name of the group on the cluster", max_length=64),
        ),
        migrations.AlterField(
            model_name="hpcgroupchangerequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment on request or revision",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupchangerequest",
            name="group",
            field=models.ForeignKey(
                help_text="Group the request belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcgroup",
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupchangerequest",
            name="requester",
            field=models.ForeignKey(
                help_text="User creating the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupchangerequestversion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment on request or revision",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupchangerequestversion",
            name="group",
            field=models.ForeignKey(
                help_text="Group the request belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcgroup",
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupchangerequestversion",
            name="requester",
            field=models.ForeignKey(
                help_text="User creating the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupcreaterequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment on request or revision",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupcreaterequest",
            name="group",
            field=models.ForeignKey(
                help_text="Group the request belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcgroup",
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupcreaterequest",
            name="requester",
            field=models.ForeignKey(
                help_text="User creating the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupcreaterequestversion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment on request or revision",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupcreaterequestversion",
            name="group",
            field=models.ForeignKey(
                help_text="Group the request belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcgroup",
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupcreaterequestversion",
            name="requester",
            field=models.ForeignKey(
                help_text="User creating the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupdeleterequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment on request or revision",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupdeleterequest",
            name="group",
            field=models.ForeignKey(
                help_text="Group the request belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcgroup",
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupdeleterequest",
            name="requester",
            field=models.ForeignKey(
                help_text="User creating the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupdeleterequestversion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment on request or revision",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupdeleterequestversion",
            name="group",
            field=models.ForeignKey(
                help_text="Group the request belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcgroup",
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupdeleterequestversion",
            name="requester",
            field=models.ForeignKey(
                help_text="User creating the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupversion",
            name="folder",
            field=models.CharField(
                help_text="Path to the group folder on the cluster",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupversion",
            name="name",
            field=models.CharField(help_text="Name of the group on the cluster", max_length=64),
        ),
        migrations.AlterField(
            model_name="hpcuserchangerequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment on request or revision",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserchangerequest",
            name="requester",
            field=models.ForeignKey(
                help_text="User creating the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserchangerequestversion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment on request or revision",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserchangerequestversion",
            name="requester",
            field=models.ForeignKey(
                help_text="User creating the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hpcusercreaterequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment on request or revision",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcusercreaterequest",
            name="requester",
            field=models.ForeignKey(
                help_text="User creating the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hpcusercreaterequestversion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment on request or revision",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcusercreaterequestversion",
            name="requester",
            field=models.ForeignKey(
                help_text="User creating the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserdeleterequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment on request or revision",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserdeleterequest",
            name="requester",
            field=models.ForeignKey(
                help_text="User creating the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserdeleterequestversion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Comment on request or revision",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserdeleterequestversion",
            name="requester",
            field=models.ForeignKey(
                help_text="User creating the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hpcgroup",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="hpcgroupchangerequestversion",
            unique_together={("belongs_to", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="hpcgroupcreaterequestversion",
            unique_together={("belongs_to", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="hpcgroupdeleterequestversion",
            unique_together={("belongs_to", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="hpcgroupversion",
            unique_together={("name", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="hpcuser",
            unique_together={("username",)},
        ),
        migrations.AlterUniqueTogether(
            name="hpcuserchangerequestversion",
            unique_together={("belongs_to", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="hpcuserdeleterequestversion",
            unique_together={("belongs_to", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="hpcuserversion",
            unique_together={("username", "version")},
        ),
        migrations.RemoveField(
            model_name="hpcgroupcreaterequestversion",
            name="delegate",
        ),
        migrations.RemoveField(
            model_name="hpcuserchangerequestversion",
            name="group",
        ),
        migrations.RemoveField(
            model_name="hpcuserdeleterequestversion",
            name="group",
        ),
    ]
