# Generated by Django 4.0.2 on 2022-03-24 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "usersec",
            "0004_remove_hpcgroupcreaterequest_delegate_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hpcgroupchangerequest",
            name="editor",
            field=models.ForeignKey(
                help_text="User editing the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupchangerequestversion",
            name="editor",
            field=models.ForeignKey(
                help_text="User editing the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupcreaterequest",
            name="editor",
            field=models.ForeignKey(
                help_text="User editing the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupcreaterequestversion",
            name="editor",
            field=models.ForeignKey(
                help_text="User editing the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupdeleterequest",
            name="editor",
            field=models.ForeignKey(
                help_text="User editing the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupdeleterequestversion",
            name="editor",
            field=models.ForeignKey(
                help_text="User editing the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hpcuserchangerequest",
            name="editor",
            field=models.ForeignKey(
                help_text="User editing the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hpcuserchangerequestversion",
            name="editor",
            field=models.ForeignKey(
                help_text="User editing the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hpcusercreaterequest",
            name="editor",
            field=models.ForeignKey(
                help_text="User editing the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hpcusercreaterequestversion",
            name="editor",
            field=models.ForeignKey(
                help_text="User editing the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hpcuserdeleterequest",
            name="editor",
            field=models.ForeignKey(
                help_text="User editing the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hpcuserdeleterequestversion",
            name="editor",
            field=models.ForeignKey(
                help_text="User editing the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_editor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
