# Generated by Django 4.0.3 on 2022-04-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersec", "0007_hpcusercreaterequest_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hpcusercreaterequest",
            name="email",
            field=models.EmailField(
                help_text="Email of user to send an invitation to", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="hpcusercreaterequestversion",
            name="email",
            field=models.EmailField(
                help_text="Email of user to send an invitation to", max_length=254
            ),
        ),
    ]
