# Generated by Django 4.0.3 on 2022-04-14 13:50

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import usersec.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usersec", "0008_alter_hpcusercreaterequest_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HpcProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Record UUID", unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                ("resources_requested", models.JSONField()),
                ("resources_used", models.JSONField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(help_text="Description of the groups work", max_length=512),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIAL", "INITIAL"),
                            ("ACTIVE", "ACTIVE"),
                            ("DELETED", "DELETED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="INITIAL",
                        help_text="Status of the project object",
                        max_length=16,
                    ),
                ),
                (
                    "gid",
                    models.IntegerField(help_text="Id of the project on the cluster", null=True),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the project on the cluster", max_length=64),
                ),
                (
                    "folder",
                    models.CharField(
                        help_text="Path to the project folder on the cluster", max_length=64
                    ),
                ),
                ("expiration", models.DateTimeField(help_text="Expiration date of the project")),
                (
                    "current_version",
                    models.IntegerField(help_text="Currently active version of the project object"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="User creating the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        blank=True,
                        help_text="User registered as delegate of the project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_delegate",
                        to="usersec.hpcuser",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group that requested project. Group PI is owner of project",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="usersec.hpcgroup",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        help_text="Members of the project",
                        related_name="%(class)s_members",
                        to="usersec.hpcuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("name",)},
            },
            bases=(usersec.models.VersionManagerMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HpcProjectChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Record UUID", unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIAL", "INITIAL"),
                            ("ACTIVE", "ACTIVE"),
                            ("REVISION", "REVISION"),
                            ("REVISED", "REVISED"),
                            ("APPROVED", "APPROVED"),
                            ("DENIED", "DENIED"),
                            ("RETRACTED", "RETRACTED"),
                        ],
                        default="INITIAL",
                        help_text="Status of the request",
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField(help_text="Comment request or summarize revision")),
                ("resources_requested", models.JSONField()),
                ("expiration", models.DateTimeField(help_text="Expiration date of the project")),
                (
                    "current_version",
                    models.IntegerField(
                        help_text="Currently active version of the project change request object"
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        blank=True,
                        help_text="User registered as delegate of the project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_delegate",
                        to="usersec.hpcuser",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        help_text="User editing the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_editor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        help_text="Members of the project",
                        related_name="%(class)s_members",
                        to="usersec.hpcuser",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project the request belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="usersec.hpcproject",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="User creating the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requester",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                usersec.models.RequestManagerMixin,
                usersec.models.VersionManagerMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="HpcProjectCreateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Record UUID", unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIAL", "INITIAL"),
                            ("ACTIVE", "ACTIVE"),
                            ("REVISION", "REVISION"),
                            ("REVISED", "REVISED"),
                            ("APPROVED", "APPROVED"),
                            ("DENIED", "DENIED"),
                            ("RETRACTED", "RETRACTED"),
                        ],
                        default="INITIAL",
                        help_text="Status of the request",
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField(help_text="Comment request or summarize revision")),
                ("resources_requested", models.JSONField()),
                ("expiration", models.DateTimeField(help_text="Expiration date of the project")),
                (
                    "current_version",
                    models.IntegerField(
                        help_text="Currently active version of the project create request object"
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        blank=True,
                        help_text="User registered as delegate of the project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_delegate",
                        to="usersec.hpcuser",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        help_text="User editing the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_editor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group the request belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="usersec.hpcgroup",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        help_text="Members of the project",
                        related_name="%(class)s_members",
                        to="usersec.hpcuser",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project the request belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="usersec.hpcproject",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="User creating the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requester",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                usersec.models.RequestManagerMixin,
                usersec.models.VersionManagerMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="HpcProjectDeleteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Record UUID", unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIAL", "INITIAL"),
                            ("ACTIVE", "ACTIVE"),
                            ("REVISION", "REVISION"),
                            ("REVISED", "REVISED"),
                            ("APPROVED", "APPROVED"),
                            ("DENIED", "DENIED"),
                            ("RETRACTED", "RETRACTED"),
                        ],
                        default="INITIAL",
                        help_text="Status of the request",
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField(help_text="Comment request or summarize revision")),
                (
                    "current_version",
                    models.IntegerField(
                        help_text="Currently active version of the project delete request object"
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        help_text="User editing the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_editor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project the request belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="usersec.hpcproject",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="User creating the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requester",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                usersec.models.RequestManagerMixin,
                usersec.models.VersionManagerMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupchangerequest",
            name="delegate",
            field=models.ForeignKey(
                blank=True,
                help_text="User registered as delegate of the group",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_delegate",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupchangerequestversion",
            name="delegate",
            field=models.ForeignKey(
                blank=True,
                help_text="User registered as delegate of the group",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_delegate",
                to="usersec.hpcuser",
            ),
        ),
        migrations.CreateModel(
            name="HpcProjectCreateRequestVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Record UUID", unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIAL", "INITIAL"),
                            ("ACTIVE", "ACTIVE"),
                            ("REVISION", "REVISION"),
                            ("REVISED", "REVISED"),
                            ("APPROVED", "APPROVED"),
                            ("DENIED", "DENIED"),
                            ("RETRACTED", "RETRACTED"),
                        ],
                        default="INITIAL",
                        help_text="Status of the request",
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField(help_text="Comment request or summarize revision")),
                ("resources_requested", models.JSONField()),
                ("expiration", models.DateTimeField(help_text="Expiration date of the project")),
                (
                    "version",
                    models.IntegerField(
                        help_text="Version number of this project create request object"
                    ),
                ),
                (
                    "belongs_to",
                    models.ForeignKey(
                        help_text="Object this version belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_history",
                        to="usersec.hpcprojectcreaterequest",
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        blank=True,
                        help_text="User registered as delegate of the project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_delegate",
                        to="usersec.hpcuser",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        help_text="User editing the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_editor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group the request belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="usersec.hpcgroup",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        help_text="Members of the project",
                        related_name="%(class)s_members",
                        to="usersec.hpcuser",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project the request belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="usersec.hpcproject",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="User creating the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requester",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HpcProjectVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Record UUID", unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                ("resources_requested", models.JSONField()),
                ("resources_used", models.JSONField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(help_text="Description of the groups work", max_length=512),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIAL", "INITIAL"),
                            ("ACTIVE", "ACTIVE"),
                            ("DELETED", "DELETED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="INITIAL",
                        help_text="Status of the project object",
                        max_length=16,
                    ),
                ),
                (
                    "gid",
                    models.IntegerField(help_text="Id of the project on the cluster", null=True),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the project on the cluster", max_length=64),
                ),
                (
                    "folder",
                    models.CharField(
                        help_text="Path to the project folder on the cluster", max_length=64
                    ),
                ),
                ("expiration", models.DateTimeField(help_text="Expiration date of the project")),
                ("version", models.IntegerField(help_text="Version number of this project object")),
                (
                    "belongs_to",
                    models.ForeignKey(
                        help_text="Object this version belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_history",
                        to="usersec.hpcproject",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="User creating the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        blank=True,
                        help_text="User registered as delegate of the project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_delegate",
                        to="usersec.hpcuser",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group that requested project. Group PI is owner of project",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="usersec.hpcgroup",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        help_text="Members of the project",
                        related_name="%(class)s_members",
                        to="usersec.hpcuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="HpcProjectDeleteRequestVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Record UUID", unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIAL", "INITIAL"),
                            ("ACTIVE", "ACTIVE"),
                            ("REVISION", "REVISION"),
                            ("REVISED", "REVISED"),
                            ("APPROVED", "APPROVED"),
                            ("DENIED", "DENIED"),
                            ("RETRACTED", "RETRACTED"),
                        ],
                        default="INITIAL",
                        help_text="Status of the request",
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField(help_text="Comment request or summarize revision")),
                (
                    "version",
                    models.IntegerField(
                        help_text="Version number of this project delete request object"
                    ),
                ),
                (
                    "belongs_to",
                    models.ForeignKey(
                        help_text="Object this version belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_history",
                        to="usersec.hpcprojectdeleterequest",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        help_text="User editing the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_editor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project the request belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="usersec.hpcproject",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="User creating the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requester",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("belongs_to", "version")},
            },
        ),
        migrations.CreateModel(
            name="HpcProjectChangeRequestVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, help_text="Record UUID", unique=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, help_text="DateTime of creation"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIAL", "INITIAL"),
                            ("ACTIVE", "ACTIVE"),
                            ("REVISION", "REVISION"),
                            ("REVISED", "REVISED"),
                            ("APPROVED", "APPROVED"),
                            ("DENIED", "DENIED"),
                            ("RETRACTED", "RETRACTED"),
                        ],
                        default="INITIAL",
                        help_text="Status of the request",
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField(help_text="Comment request or summarize revision")),
                ("resources_requested", models.JSONField()),
                ("expiration", models.DateTimeField(help_text="Expiration date of the project")),
                (
                    "version",
                    models.IntegerField(
                        help_text="Version number of this project change request object"
                    ),
                ),
                (
                    "belongs_to",
                    models.ForeignKey(
                        help_text="Object this version belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_history",
                        to="usersec.hpcprojectchangerequest",
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        blank=True,
                        help_text="User registered as delegate of the project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_delegate",
                        to="usersec.hpcuser",
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        help_text="User editing the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_editor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        help_text="Members of the project",
                        related_name="%(class)s_members",
                        to="usersec.hpcuser",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project the request belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="usersec.hpcproject",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="User creating the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requester",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("belongs_to", "version")},
            },
        ),
    ]
