# Generated by Django 4.0.3 on 2022-04-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usersec", "0009_hpcproject_hpcprojectchangerequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hpcprojectchangerequest",
            name="description",
            field=models.CharField(
                help_text="Additional information about the user", max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="hpcprojectchangerequestversion",
            name="description",
            field=models.CharField(
                help_text="Additional information about the user", max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="hpcprojectcreaterequest",
            name="description",
            field=models.CharField(
                default="some description",
                help_text="Additional information about the user",
                max_length=512,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hpcprojectcreaterequest",
            name="name",
            field=models.CharField(
                default="some-project", help_text="Description of the groups work", max_length=512
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hpcprojectcreaterequestversion",
            name="description",
            field=models.CharField(
                default="some description",
                help_text="Additional information about the user",
                max_length=512,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hpcprojectcreaterequestversion",
            name="name",
            field=models.CharField(
                default="some-project", help_text="Description of the groups work", max_length=512
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hpcproject",
            name="group",
            field=models.ForeignKey(
                help_text="Group that requested project. Group PI is owner of project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcgroup",
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectcreaterequest",
            name="group",
            field=models.ForeignKey(
                help_text="Group the request belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcgroup",
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectcreaterequestversion",
            name="group",
            field=models.ForeignKey(
                help_text="Group the request belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcgroup",
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectversion",
            name="group",
            field=models.ForeignKey(
                help_text="Group that requested project. Group PI is owner of project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="usersec.hpcgroup",
            ),
        ),
    ]
