# Generated by Django 4.0.3 on 2022-04-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersec", "0010_hpcprojectchangerequest_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hpcgroupchangerequest",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupchangerequestversion",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupcreaterequest",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupcreaterequestversion",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupdeleterequest",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupdeleterequestversion",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectchangerequest",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectchangerequestversion",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectcreaterequest",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectcreaterequestversion",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectdeleterequest",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectdeleterequestversion",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserchangerequest",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserchangerequestversion",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcusercreaterequest",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcusercreaterequestversion",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserdeleterequest",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserdeleterequestversion",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Comment request or summarize revision", null=True
            ),
        ),
    ]
