# Generated by Django 4.0.3 on 2022-05-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usersec", "0011_alter_hpcgroupchangerequest_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hpcgroup",
            name="delegate",
            field=models.ForeignKey(
                blank=True,
                help_text="The optional delegate can act on behalf of the project owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_delegate",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroup",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Concise description of what kind of computations the group performs on the cluster",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupchangerequest",
            name="delegate",
            field=models.ForeignKey(
                blank=True,
                help_text="The optional delegate can act on behalf of the group owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_delegate",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupchangerequestversion",
            name="delegate",
            field=models.ForeignKey(
                blank=True,
                help_text="The optional delegate can act on behalf of the group owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_delegate",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupcreaterequest",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Concise description of what kind of computations the group performs on the cluster",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupcreaterequestversion",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Concise description of what kind of computations the group performs on the cluster",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupversion",
            name="delegate",
            field=models.ForeignKey(
                blank=True,
                help_text="The optional delegate can act on behalf of the project owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_delegate",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupversion",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Concise description of what kind of computations the group performs on the cluster",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcproject",
            name="delegate",
            field=models.ForeignKey(
                blank=True,
                help_text="The optional delegate can act on behalf of the project owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_delegate",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AlterField(
            model_name="hpcproject",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Concise description of what kind of computations are required for the project on the cluster",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectchangerequest",
            name="delegate",
            field=models.ForeignKey(
                blank=True,
                help_text="The optional delegate can act on behalf of the project owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_delegate",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectchangerequest",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Additional information about the user",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectchangerequestversion",
            name="delegate",
            field=models.ForeignKey(
                blank=True,
                help_text="The optional delegate can act on behalf of the project owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_delegate",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectchangerequestversion",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Additional information about the user",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectcreaterequest",
            name="delegate",
            field=models.ForeignKey(
                blank=True,
                help_text="The optional delegate can act on behalf of the project owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_delegate",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectcreaterequest",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Concise description of what kind of computations are required for the project on the cluster",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectcreaterequest",
            name="name",
            field=models.CharField(
                help_text="Please use only alphanumeric characters, dashes or underscores and no spaces",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectcreaterequestversion",
            name="delegate",
            field=models.ForeignKey(
                blank=True,
                help_text="The optional delegate can act on behalf of the project owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_delegate",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectcreaterequestversion",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Concise description of what kind of computations are required for the project on the cluster",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectcreaterequestversion",
            name="name",
            field=models.CharField(
                help_text="Please use only alphanumeric characters, dashes or underscores and no spaces",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectversion",
            name="delegate",
            field=models.ForeignKey(
                blank=True,
                help_text="The optional delegate can act on behalf of the project owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_delegate",
                to="usersec.hpcuser",
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectversion",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Concise description of what kind of computations are required for the project on the cluster",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcuser",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Additional information about the user",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserversion",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Additional information about the user",
                max_length=512,
                null=True,
            ),
        ),
    ]
