# Generated by Django 4.2.10 on 2024-02-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usersec", "0016_alter_hpcproject_group_alter_hpcprojectversion_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hpcuser",
            name="uid",
        ),
        migrations.RemoveField(
            model_name="hpcuserversion",
            name="uid",
        ),
    ]
