# Generated by Django 4.2.10 on 2024-02-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usersec", "0017_remove_hpcuser_uid_remove_hpcuserversion_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="hpcuser",
            name="home_directory",
            field=models.CharField(
                default="/data/cephfs-1/home/users/{user.username}",
                help_text="Path to the user home directory on the cluster",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hpcuser",
            name="login_shell",
            field=models.CharField(
                choices=[
                    ("/usr/bin/bash", "/usr/bin/bash"),
                    ("/usr/bin/fish", "/usr/bin/fish"),
                    ("/usr/bin/zsh", "/usr/bin/zsh"),
                    ("/usr/bin/sh", "/usr/bin/sh"),
                ],
                default="/usr/bin/bash",
                help_text="Login shell of the user on the cluster",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="hpcuserversion",
            name="home_directory",
            field=models.CharField(
                default="/data/cephfs-1/home/users/{user.username}",
                help_text="Path to the user home directory on the cluster",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hpcuserversion",
            name="login_shell",
            field=models.CharField(
                choices=[
                    ("/usr/bin/bash", "/usr/bin/bash"),
                    ("/usr/bin/fish", "/usr/bin/fish"),
                    ("/usr/bin/zsh", "/usr/bin/zsh"),
                    ("/usr/bin/sh", "/usr/bin/sh"),
                ],
                default="/usr/bin/bash",
                help_text="Login shell of the user on the cluster",
                max_length=32,
            ),
        ),
    ]
