# Generated by Django 4.2.10 on 2024-02-16 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usersec", "0019_alter_hpcuser_primary_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hpcprojectcreaterequest",
            name="delegate",
        ),
        migrations.RemoveField(
            model_name="hpcprojectcreaterequestversion",
            name="delegate",
        ),
    ]
