# Generated by Django 4.2.10 on 2024-02-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usersec", "0020_remove_hpcprojectcreaterequest_delegate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hpcgroupcreaterequest",
            name="group_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the group on the cluster",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupcreaterequestversion",
            name="group_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the group on the cluster",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupchangerequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupchangerequestversion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupcreaterequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupcreaterequestversion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupdeleterequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcgroupdeleterequestversion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectchangerequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectchangerequestversion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectcreaterequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectcreaterequestversion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectdeleterequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectdeleterequestversion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserchangerequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserchangerequestversion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcusercreaterequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcusercreaterequestversion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserdeleterequest",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcuserdeleterequestversion",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="This field is for communication between you and the HPC team.",
                null=True,
            ),
        ),
    ]
