# Generated by Django 4.2.13 on 2024-07-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersec", "0026_termsandconditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="hpcgroup",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupchangerequest",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupchangerequestversion",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupcreaterequest",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupcreaterequestversion",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupdeleterequest",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupdeleterequestversion",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupinvitation",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupinvitationversion",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcgroupversion",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcproject",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcprojectchangerequest",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcprojectchangerequestversion",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcprojectcreaterequest",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcprojectcreaterequestversion",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcprojectdeleterequest",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcprojectdeleterequestversion",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcprojectinvitation",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcprojectinvitationversion",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcprojectversion",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcuser",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcuserchangerequest",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcuserchangerequestversion",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcusercreaterequest",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcusercreaterequestversion",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcuserdeleterequest",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcuserdeleterequestversion",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
        migrations.AddField(
            model_name="hpcuserversion",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="DateTime of last modification"
            ),
        ),
    ]
