# Generated by Django 5.1 on 2024-08-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersec", "0027_hpcgroup_date_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hpcprojectcreaterequest",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Concise description of what kind of computations are required for the project on the cluster",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hpcprojectcreaterequestversion",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Concise description of what kind of computations are required for the project on the cluster",
                max_length=512,
                null=True,
            ),
        ),
    ]
