name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_DB: hpcaccess
          POSTGRES_USER: hpcaccess
          POSTGRES_PASSWORD: hpcaccess
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 5432:5432
    env:
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_PORT: 5432
      DATABASE_URL: 'postgres://hpcaccess:hpcaccess@0.0.0.0/hpcaccess'
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install project Python dependencies
        run: |
          pip install wheel==0.37.1
          pip install -r requirements/local.txt
      - name: Download icons
        run: python manage.py geticons
      - name: Run collectstatic
        run: python manage.py collectstatic --noinput
      - name: Run tests
        run: |
          coverage run --rcfile=.coveragerc manage.py test -v 2 --settings=config.settings.test
          coverage xml
          coverage report
      - name: Check linting
        run: flake8 .
      - name: Check formatting
        run: make black arg=--check
      - name: Run Codacy coverage reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
