name: CI

on:
  - push
  - pull_request

jobs:
  Python-Test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: hpcaccess
          POSTGRES_USER: hpcaccess
          POSTGRES_PASSWORD: hpcaccess
          DATABASE_URL: postgres://hpcaccess:hpcaccess@postgres/hpcaccess
          CELERY_BROKER_URL: redis://redis:6379/0
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 5432:5432

    env:
      CELERY_BROKER_URL: redis://0.0.0.0:6379/0
      DATABASE_URL: 'postgres://hpcaccess:hpcaccess@0.0.0.0/hpcaccess'
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_PORT: 5432

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zlib1g-dev libtiff5-dev libjpeg8-dev \
              libfreetype6-dev liblcms2-dev libwebp-dev libpq-dev graphviz-dev \
              libldap2-dev libsasl2-dev

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install project dependencies
        run: uv sync --group dev --extra ldap

      - name: Download icons
        run: uv run python manage.py geticons

      - name: Run collectstatic
        run: uv run python manage.py collectstatic --noinput

      - name: Run tests
        run: |
          uv run coverage run manage.py test -v 2 --settings=config.settings.test
          uv run coverage xml
          uv run coverage report

  Python-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install project dependencies
        run: uv sync --group dev

      - name: Style, linting and sorting with ruff
        uses: chartboost/ruff-action@v1
        with:
          version: v0.4.2
